name: Docker Image CI

on:
  push:
    branches: ["feature/program-coordinator"]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm test

  buildAndPublish:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t ${{secrets.CI_REG_PATH}}/techmodel-backend:latest .

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{secrets.CI_REG_PATH}}
          username: ${{secrets.CI_REG_USERNAME}}
          password: ${{secrets.CI_REG_PASSWORD}}

      - name: Publish the Docker image
        run: docker push ${{secrets.CI_REG_PATH}}/techmodel-backend:latest
