name: Docker Image CI

on:
  push:
    branches: ["feature/azure-deployment"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Build the Docker image
        run: docker build -t techmodel.azurecr.io/techmodel-backend:latest

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: techmodel.azurecr.io
          username: techmodel
          password: 1vgBVm/y/pEJfjsePY1ZEjfH9ZSHKQiH

      - name: Publish the Docker image
        run: docker push techmodel.azurecr.io/techmodel-backend:latest
